apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus3
  name: nexus3
  namespace: default
spec:
  ports:
  - name: gui
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: docker
    port: 8123
    protocol: TCP
    targetPort: 8123 
  selector:
    app: nexus3
  sessionAffinity: None
  type: ClusterIP
