apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus3
  name: nexus3
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus3
  sessionAffinity: None
  type: LoadBalancer
