apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: jenkins
  name: jenkins
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: pgsql-data-permission-fix
        image: busybox
        #command: ["/bin/chmod","-R","755", "/var/jenkins_home/"]
        command: ["/bin/chown","-R","1000", "/var/jenkins_home/"]
        volumeMounts:
        - name: jenkinshome
          mountPath: /var/jenkins_home/
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: Always
        name: jenkins
        volumeMounts:
        - name: jenkinshome
          mountPath: /var/jenkins_home/
      volumes:
      - name: jenkinshome
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: jenkinshome
            clusterNamespace: rook-ceph
            #path: "/"
 
