apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camunda
  name: camunda
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: camunda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: camunda
    spec:
      containers:
      - image: camunda/camunda-bpm-platform:latest
        imagePullPolicy: Always
        name: camunda-bpm-platform
        resources: {}
        envFrom:
          - configMapRef:
              name: camunda-config
          - secretRef:
              name: camunda-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
