apiVersion: v1
kind: Service
metadata:
  labels:
    app: camunda
  name: camunda
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30308
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: camunda
  sessionAffinity: None
  type: LoadBalancer
