apiVersion: v1
data:
  DB_DRIVER: oracle.jdbc.OracleDriver
  DB_URL: "jdbc:oracle:thin:@192.168.1.220:1521:tdb1"
  DB_USERNAME: camunda
  WAIT_FOR: 192.168.1.220:1521
  JAVA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=192.168.1.241 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9000"
kind: ConfigMap
metadata:
  name: camunda-config
  namespace: default
