apiVersion: v1
kind: Service
metadata:
  labels:
    app: camunda
  name: camunda
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: camunda-http-port
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: camunda-jmx-port
  selector:
    app: camunda
  sessionAffinity: None
  type: LoadBalancer
